apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: lhc-lh-strimzicon
  namespace: strimzicon
  labels:
    littlehorse.io/cluster: lh-strimzicon
    strimzi.io/cluster: strimzicon
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - operations:
      - Describe
      - DescribeConfigs
      - IdempotentWrite
      - Write
      - Read
      - Create
      - ClusterAction
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: topic
    - operations:
      - All
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: group
    - operations:
      - All
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: transactionalId
    type: simple
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
data:
  LHS_ADVERTISED_LISTENERS: internal://lh-strimzicon-server.strimzicon.svc.cluster.local:2023,external://lh.strimzicon.demo:2024
  LHS_CLUSTER_ID: lh-strimzicon
  LHS_CLUSTER_PARTITIONS: "12"
  LHS_CORE_STREAM_THREADS: "3"
  LHS_INSTANCE_ID: "0"
  LHS_INTERNAL_ADVERTISED_HOST: lh-strimzicon-server
  LHS_INTERNAL_ADVERTISED_PORT: "2011"
  LHS_INTERNAL_BIND_PORT: "2011"
  LHS_KAFKA_BOOTSTRAP_SERVERS: strimzicon-kafka-internal-bootstrap:9093
  LHS_KAFKA_SASL_JAAS_CONFIG_FILE: /lh-secrets/sasl.jaas.config
  LHS_KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  LHS_KAFKA_SECURITY_PROTOCOL: SASL_SSL
  LHS_KAFKA_TRUSTSTORE: /kafka-secrets/ca.p12
  LHS_KAFKA_TRUSTSTORE_PASSWORD_FILE: /kafka-secrets/ca.password
  LHS_LISTENERS: internal:2023,external:2024
  LHS_LISTENERS_AUTHENTICATION_MAP: internal:NONE,external:NONE
  LHS_LISTENERS_PROTOCOL_MAP: internal:PLAIN,external:PLAIN
  LHS_NUM_NETWORK_THREADS: "3"
  LHS_REPLICATION_FACTOR: "3"
  LHS_ROCKSDB_COMPACTION_THREADS: "4"
  LHS_ROCKSDB_TOTAL_BLOCK_CACHE_BYTES: "268435456"
  LHS_ROCKSDB_TOTAL_MEMTABLE_BYTES: "1610612736"
  LHS_SHOULD_CREATE_TOPICS: "true"
  LHS_STATE_DIR: /lh-data/streams
  LHS_STREAMS_NUM_STANDBY_REPLICAS: "0"
  LHS_STREAMS_NUM_WARMUP_REPLICAS: "6"
  LHS_STREAMS_SESSION_TIMEOUT: "45000"
  LHS_TIMER_STREAM_THREADS: "1"
---
################ POD ##############

apiVersion: v1
kind: Pod
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
  labels:
    littlehorse.io/server: lh-strimzicon-server
spec:
  containers:
  - args:
    - server
    envFrom:
    - configMapRef:
        name: lh-strimzicon-server
        optional: false
    image: ghcr.io/littlehorse-enterprises/littlehorse/lh-server:0.13.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /liveness
        port: 1822
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    name: lh-server
    ports:
    - containerPort: 2023
      name: internal
      protocol: TCP
    - containerPort: 2024
      name: external
      protocol: TCP
    - containerPort: 2011
      name: internal-comms
      protocol: TCP
    - containerPort: 1822
      name: health-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /liveness
        port: 1822
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lh-data/
      name: lh-data
    - mountPath: /kafka-secrets/
      name: kafka-secrets
    - mountPath: /lh-secrets/
      name: lh-secrets
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - name: kafka-secrets
    secret:
      secretName: strimzicon-cluster-ca-cert
  - name: lh-secrets
    secret:
      defaultMode: 420
      secretName: lhc-lh-strimzicon
  - configMap:
      defaultMode: 420
      name: lh-strimzicon-server
    name: lh-config
  - name: lh-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
spec:
  ports:
  - name: internal
    port: 2023
    protocol: TCP
    targetPort: 2023
  selector:
    littlehorse.io/server: lh-strimzicon-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lh-strimzicon-dashboard
  namespace: strimzicon
  labels:
    app: lh-strimzicon-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lh-strimzicon-dashboard
  template:
    metadata:
      labels:
        app: lh-strimzicon-dashboard
    spec:
      containers:
        - name: lh-dashboard
          image: ghcr.io/littlehorse-enterprises/littlehorse/lh-dashboard:latest
          env:
            - name: LHC_API_HOST
              value: lh-strimzicon-server.strimzicon.svc.cluster.local
            - name: LHC_API_PORT
              value: "2023"
            - name: LHC_OAUTH_ENABLED
              value: "false"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: lh-strimzicon-dashboard
  namespace: strimzicon
  labels:
    app: lh-strimzicon-dashboard
spec:
  selector:
    app: lh-strimzicon-dashboard
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lh-strimzicon-dashboard
  namespace: strimzicon
spec:
  parentRefs:
    - name: my-gateway
      namespace: strimzicon
  hostnames:
    - lh-dashboard.strimzicon.demo
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lh-strimzicon-dashboard
          port: 3000
