# One node
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080
    # Port 80 for the HTTPRoute to acccess LittleHorse Dashboard
    hostPort: 80
    protocol: TCP
  - containerPort: 30092
    # Port 9092 on the host machine is for Kafka!
    hostPort: 9092
    protocol: TCP
  - containerPort: 32023
    # Port 2023 on the host machine is for LittleHorse Server.
    hostPort: 2023
    protocol: TCP
containerdConfigPatches:
# Some magic to aid in the linkage of the docker image registry to the
# KIND cluster network
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
    endpoint = ["http://kind-registry:5000"]
