apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: lhc-lh-strimzicon
  namespace: strimzicon
  labels:
    littlehorse.io/cluster: lh-strimzicon
    strimzi.io/cluster: strimzicon
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: lh-kafkauser-creds
          key: password
  authorization:
    acls:
    - operations:
      - Describe
      - DescribeConfigs
      - IdempotentWrite
      - Write
      - Read
      - Create
      - ClusterAction
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: topic
    - operations:
      - All
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: group
    - operations:
      - All
      resource:
        name: lh-strimzicon-
        patternType: prefix
        type: transactionalId
    type: simple
---
apiVersion: v1
kind: Secret
metadata:
  name: lh-kafkauser-creds
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster  # Match your Kafka cluster name
type: Opaque
stringData:
  password: HjKJZgxbxvkvOEGlDZtCZQEvtCQvach2
---
apiVersion: v1
kind: Secret
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
type: Opaque
data:
  ca.p12: MIIGogIBAzCCBkwGCSqGSIb3DQEHAaCCBj0EggY5MIIGNTCCBjEGCSqGSIb3DQEHBqCCBiIwggYeAgEAMIIGFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQGr3IlX9bDlYtBgFTQo2T3bMEMGQICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEECaMw0dfXePvpkaXPJbOAwqAggWgOesZdQoH9G5Tk2hFRMijGO+r1rbENEvWxQUI/siEcIavmQhmvxBo98ZLGf6PuSdnVZCxwE5gp33In3QGgZM28CGYdZY6zhCp92sQwFoU0z6x2WaMagCldwOqwTE/Oy8kkbOvreGRefUIIl/ya0ywL5Qp56TzD0UK2AEAQWAKWryFRV/mcAAqnznUiaRhjtnwfaoMGl4BH4dgxK8rtHUCMmCeN9S9RcIwEUHNIhoPupzs6O/stNgQmig19iSZ05uUv9fyd/wJy0ILmFl5o7Uhs6LWWfjn6hFbIokCLS/lZKwlG7Uz4SxyKLDb1NUIS9Y6hVnXtBR4qMGmyaC5J/hcFq82tHcxQaYEgy4GmYmxqZfqroxNNfcd+vbVZwILNpAg7Ldo4dTIUYCsUPgBg4uNQcr+h3rXY7A9JK2O1j88cvzBNo1vbzmjMsIYD4pztyrFBO6aGNYXoOODYLdm1EDRAZcNYJ10nY/QuvGJDFDLUjYkOWpqhFE23QPvy3mLRO/Ol/gxSn/fBTLZ8Vh56ipxTsJxyh7SewpTIg/0AOkLtcxdVLyxFlZ+DE7Q7ym0gxCwVdy+T0hIhNICOh8sWkzV5QFRzL8r87sIQXb7xpWkOB3lwKi1+qfTBZ54YwFmRp4gKwWcLOLxO3nWKIKjp8vNOi0TVwTTKDHTfs7E5UZmeWZcGKqz/hWgaUCSkX15x3dvDXPb+3bHodTNGa00ur8ldCbE+ccJxknqWmh3744Puo8nR45+ttrD7V1lrrgBFzXvUmLaeQJ8ZF3FQbyQIw52zpqNCQRcW72/d0PGQrVW+IhjH7UIg1ZaPcc2g/h5ETxGrKMojGm33fBNvjfrBYiBsQ760YT3UvyYoEXovaXfqgfTUPfUla9niY5t0JQVoSIDKIBrksA4b/dtw0ISdlOzzVB+rBkQpwjHpjdXsV/ZeFmbegwVHsy1VYqfPimYuBPTSYkybQkdo7GYx3QW7QYCEHNYxl0Ltds2k6Y/upsfKuvJBAMQXAdzTVNONgINslWKef4ymxYKXP8LMbXIxSOF0g6wDbUNw9wh4ZcswLTZsqzrZ5OLdfaZOwQcbL86iM20ICd3OFCAnTShKi8mH3vT9I4kFanQ7daKhoNfT2PJYiFtYm2NMr/Ctn+OVQiMqg6uf5mQvydSf/jTJfPw5LHyTWw95SKEqrtQ6DQru9A2DJxPrnZBIYvHc5x2wOfI1l7AiDApouzGX66wOYeQSNWwAKrHbNUegyXRa52942Pnwc8hL6jy8yws2u15HK63LrM2Y2sOZFOZpPstWU0LCpfeXInIIhiPv0LOYhEF/CL3Puh2kWgcsIKA/aRrgvHyyDiSNVv/0BSRMfabskhJEWZdFsgnQuEENJ6rekpqRKfSRsZLdEmTz5S6mGDHOmVaOhbqaHDrS4mGhACpd0kt137MEu4MWwus+63cejsffuSGffhuyJtpGeK+aPE3NnizAUM58OfEtReJPbJwS9MRijsMdvbpHtD10zr4bZ6MGREsnjp1/xhfszm9mSexfXo2mwGIgCdy0ZOViGOK0/KaR2N3YN34bNcTMyX1i6k2AyadzWwmpDVQr1dm8gZKuvsdXOmmhonVhEo6jD3vYPiDTvbarHIS+ougiNUkieir9ri7HEInNshAb+fCgR1xeIZx30OpuiKyes2AH1sjkzBdmOTHR37O1in+KZAH/ih4MPmvYHIJAY6H+CTuwXICGP2QU8l6z4ztezi99CwdedLorbY0ag7gjj0CueZlLtkTOfphLpG4kgOdA4ZgGknn9EgbtLOu4vx7rIxA2xt4sY3X2vdiIOmqppWDaG9uJ5YJyFB8OqhmQL1RcJQ6AUBPLy6Q/dXMo3XGWo0Y31La0RxQU5ALZYbyMtHEU5tBxLNT/DJ5v2c63N+eZ6hMLEcwXi+PlWxjME0wMTANBglghkgBZQMEAgEFAAQgDfuDOMm5Er+M+xHO1ZDnDTLHEeB73rTpPxQXN9ZDn7wEFEZvOyvoOzVHpp2QJPp3deWuPAFdAgInEA==
  ca.password: UzhDOWZXRUhFa1Vw
  sasl.jaas.config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0ibGhjLWxoLXN0cmltemljb24iIHBhc3N3b3JkPSJIaktKWmd4Ynh2a3ZPRUdsRFp0Q1pRRXZ0Q1F2YWNoMiI7

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
data:
  LHS_ADVERTISED_LISTENERS: internal://lh-strimzicon-server.strimzicon.svc.cluster.local:2023,external://lh.strimzicon.demo:2024
  LHS_CLUSTER_ID: lh-strimzicon
  LHS_CLUSTER_PARTITIONS: "12"
  LHS_CORE_STREAM_THREADS: "3"
  LHS_INSTANCE_ID: "0"
  LHS_INTERNAL_ADVERTISED_HOST: lh-strimzicon-server
  LHS_INTERNAL_ADVERTISED_PORT: "2011"
  LHS_INTERNAL_BIND_PORT: "2011"
  LHS_KAFKA_BOOTSTRAP_SERVERS: strimzicon-kafka-internal-bootstrap:9093
  LHS_KAFKA_SASL_JAAS_CONFIG_FILE: /lh-secrets/sasl.jaas.config
  LHS_KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  LHS_KAFKA_SECURITY_PROTOCOL: SASL_SSL
  LHS_KAFKA_TRUSTSTORE: /lh-secrets/ca.p12
  LHS_KAFKA_TRUSTSTORE_PASSWORD_FILE: /lh-secrets/ca.password
  LHS_LISTENERS: internal:2023,external:2024
  LHS_LISTENERS_AUTHENTICATION_MAP: internal:NONE,external:NONE
  LHS_LISTENERS_PROTOCOL_MAP: internal:PLAIN,external:PLAIN
  LHS_NUM_NETWORK_THREADS: "3"
  LHS_REPLICATION_FACTOR: "3"
  LHS_ROCKSDB_COMPACTION_THREADS: "4"
  LHS_ROCKSDB_TOTAL_BLOCK_CACHE_BYTES: "268435456"
  LHS_ROCKSDB_TOTAL_MEMTABLE_BYTES: "1610612736"
  LHS_SHOULD_CREATE_TOPICS: "true"
  LHS_STATE_DIR: /lh-data/streams
  LHS_STREAMS_NUM_STANDBY_REPLICAS: "0"
  LHS_STREAMS_NUM_WARMUP_REPLICAS: "6"
  LHS_STREAMS_SESSION_TIMEOUT: "45000"
  LHS_TIMER_STREAM_THREADS: "1"
---
################ POD ##############3

apiVersion: v1
kind: Pod
metadata:
  name: lh-strimzicon-server
  namespace: strimzicon
spec:
  containers:
  - args:
    - server
    envFrom:
    - configMapRef:
        name: lh-strimzicon-server
        optional: false
    image: ghcr.io/littlehorse-enterprises/littlehorse/lh-server:0.13.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /liveness
        port: 1822
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    name: lh-server
    ports:
    - containerPort: 2023
      name: internal
      protocol: TCP
    - containerPort: 2024
      name: external
      protocol: TCP
    - containerPort: 2011
      name: internal-comms
      protocol: TCP
    - containerPort: 1822
      name: health-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /liveness
        port: 1822
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lh-data/
      name: lh-data
    - mountPath: /lh-secrets/
      name: lh-secrets
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - name: lh-secrets
    secret:
      defaultMode: 420
      secretName: lh-strimzicon-server
  - configMap:
      defaultMode: 420
      name: lh-strimzicon-server
    name: lh-config
  - name: lh-data
    emptyDir: {}
